import 'package:trdl_tool/core/all_imports.dart';

ThemeData themeLight = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff004e15),
    primaryContainer: Color(0xff8fb99b),
    secondary: Color(0xff007256),
    secondaryContainer: Color(0xff83bcad),
    tertiary: Color(0xff295300),
    tertiaryContainer: Color(0xff8faa78),
    appBarColor: Color(0xff83bcad),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 25,
  appBarOpacity: 0.85,
  appBarElevation: 6,
  tabBarStyle: FlexTabBarStyle.forBackground,
  tooltipsMatchBackground: true,
  useSubThemes: true,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    blendOnColors: false,
    switchSchemeColor: SchemeColor.primary,
    checkboxSchemeColor: SchemeColor.primary,
    radioSchemeColor: SchemeColor.primary,
    unselectedToggleIsColored: true,
    fabSchemeColor: SchemeColor.primary,
    popupMenuOpacity: 0.95,
    bottomNavigationBarSelectedLabelSchemeColor: null,
    bottomNavigationBarUnselectedLabelSchemeColor: null,
    bottomNavigationBarSelectedIconSchemeColor: null,
    bottomNavigationBarUnselectedIconSchemeColor: null,
    bottomNavigationBarBackgroundSchemeColor: null,
    // bottomNavigationBarSelectedIconSize: 48.0,
    bottomNavigationBarOpacity: 0.85,
    bottomNavigationBarElevation: 6,
    navigationBarSelectedLabelSchemeColor: null,
    navigationBarUnselectedLabelSchemeColor: null,
    navigationBarSelectedIconSchemeColor: null,
    navigationBarUnselectedIconSchemeColor: null,
    navigationBarHighlightSchemeColor: null,
    navigationBarBackgroundSchemeColor: null,
    navigationBarOpacity: 0.85,
    navigationRailSelectedLabelSchemeColor: null,
    navigationRailUnselectedLabelSchemeColor: null,
    navigationRailSelectedIconSchemeColor: null,
    navigationRailUnselectedIconSchemeColor: null,
    navigationRailIndicatorSchemeColor: null,
    navigationRailBackgroundSchemeColor: null,
    navigationRailOpacity: 0.85,
    navigationRailElevation: 6,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
  ),
  useMaterial3ErrorColors: true,
  tones: FlexTones.vividSurfaces(Brightness.light),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  fontFamily: GoogleFonts.questrial().fontFamily,
);

ThemeData themeDark = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff519e67),
    primaryContainer: Color(0xff27683a),
    secondary: Color(0xff479985),
    secondaryContainer: Color(0xff00513b),
    tertiary: Color(0xff73a497),
    tertiaryContainer: Color(0xff275000),
    appBarColor: Color(0xff00513b),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 25,
  appBarOpacity: 0.85,
  appBarElevation: 6,
  tabBarStyle: FlexTabBarStyle.forBackground,
  tooltipsMatchBackground: true,
  useSubThemes: true,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 30,
    switchSchemeColor: SchemeColor.primary,
    checkboxSchemeColor: SchemeColor.primary,
    radioSchemeColor: SchemeColor.primary,
    unselectedToggleIsColored: true,
    fabSchemeColor: SchemeColor.primary,
    popupMenuOpacity: 0.95,
    bottomNavigationBarSelectedLabelSchemeColor: null,
    bottomNavigationBarUnselectedLabelSchemeColor: null,
    bottomNavigationBarSelectedIconSchemeColor: null,
    bottomNavigationBarUnselectedIconSchemeColor: null,
    bottomNavigationBarBackgroundSchemeColor: null,
    bottomNavigationBarOpacity: 0.85,
    bottomNavigationBarElevation: 6,
    navigationBarSelectedLabelSchemeColor: null,
    navigationBarUnselectedLabelSchemeColor: null,
    navigationBarSelectedIconSchemeColor: null,
    navigationBarUnselectedIconSchemeColor: null,
    navigationBarHighlightSchemeColor: null,
    navigationBarBackgroundSchemeColor: null,
    navigationBarOpacity: 0.85,
    navigationRailSelectedLabelSchemeColor: null,
    navigationRailUnselectedLabelSchemeColor: null,
    navigationRailSelectedIconSchemeColor: null,
    navigationRailUnselectedIconSchemeColor: null,
    navigationRailIndicatorSchemeColor: null,
    navigationRailBackgroundSchemeColor: null,
    navigationRailOpacity: 0.85,
    navigationRailElevation: 6,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
  ),
  useMaterial3ErrorColors: true,
  tones: FlexTones.vividSurfaces(Brightness.dark),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  fontFamily: GoogleFonts.questrial().fontFamily,
);

/*OLD FLEXCOLORSCHEME, UNCOMMENT IF ISSUES ARISE*/

// ThemeData themeLight = FlexThemeData.light(
//   scheme: FlexScheme.jungle,
//   surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
//   blendLevel: 25,
//   appBarStyle: FlexAppBarStyle.primary,
//   appBarOpacity: 0.85,
//   appBarElevation: 6,
//   transparentStatusBar: true,
//   tabBarStyle: FlexTabBarStyle.forAppBar,
//   tooltipsMatchBackground: true,
//   swapColors: false,
//   lightIsWhite: false,
//   useSubThemes: true,
//   visualDensity: FlexColorScheme.comfortablePlatformDensity,
//   fontFamily: GoogleFonts.questrial().fontFamily,
//   subThemesData: const FlexSubThemesData(
//     useTextTheme: true,
//     fabUseShape: true,
//     interactionEffects: true,
//     bottomNavigationBarOpacity: 0.85,
//     bottomNavigationBarElevation: 6,
//     inputDecoratorIsFilled: true,
//     inputDecoratorBorderType: FlexInputBorderType.outline,
//     inputDecoratorUnfocusedHasBorder: true,
//     blendOnColors: true,
//     blendTextTheme: true,
//     popupMenuOpacity: 0.95,
//   ),
// );
//
// ThemeData themeDark = FlexThemeData.dark(
//   scheme: FlexScheme.jungle,
//   surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
//   blendLevel: 25,
//   appBarStyle: FlexAppBarStyle.background,
//   appBarOpacity: 0.85,
//   appBarElevation: 6,
//   transparentStatusBar: true,
//   tabBarStyle: FlexTabBarStyle.forAppBar,
//   tooltipsMatchBackground: true,
//   swapColors: false,
//   darkIsTrueBlack: false,
//   useSubThemes: true,
//   visualDensity: FlexColorScheme.comfortablePlatformDensity,
//   fontFamily: GoogleFonts.questrial().fontFamily,
//   subThemesData: const FlexSubThemesData(
//     useTextTheme: true,
//     fabUseShape: true,
//     interactionEffects: true,
//     bottomNavigationBarOpacity: 0.85,
//     bottomNavigationBarElevation: 6,
//     inputDecoratorIsFilled: true,
//     inputDecoratorBorderType: FlexInputBorderType.outline,
//     inputDecoratorUnfocusedHasBorder: true,
//     blendOnColors: true,
//     blendTextTheme: true,
//     popupMenuOpacity: 0.95,
//   ),
// );
