import 'package:trdl_tool/all_imports.dart';

ThemeData themeLight = FlexThemeData.light(
  scheme: FlexScheme.jungle,
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 24,
  appBarOpacity: 0.85,
  transparentStatusBar: false,
  appBarElevation: 6.0,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 24,
    bottomSheetRadius: 20.0,
    switchSchemeColor: SchemeColor.primary,
    checkboxSchemeColor: SchemeColor.primary,
    radioSchemeColor: SchemeColor.primary,
    unselectedToggleIsColored: true,
    fabRadius: 20.0,
    chipRadius: 20.0,
    cardRadius: 12.0,
    popupMenuOpacity: 0.90,
    popupMenuRadius: 8.0,
    dialogRadius: 20.0,
    timePickerDialogRadius: 20.0,
    bottomNavigationBarOpacity: 0.85,
    bottomNavigationBarElevation: 6.0,
    navigationBarOpacity: 0.85,
    navigationRailOpacity: 0.85,
    navigationRailElevation: 6.0,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  fontFamily: GoogleFonts.questrial().fontFamily,
);
ThemeData themeDark = FlexThemeData.dark(
  scheme: FlexScheme.jungle,
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 15,
  appBarStyle: FlexAppBarStyle.background,
  appBarOpacity: 0.90,
  transparentStatusBar: false,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 30,
    bottomSheetRadius: 20.0,
    switchSchemeColor: SchemeColor.primary,
    checkboxSchemeColor: SchemeColor.primary,
    radioSchemeColor: SchemeColor.primary,
    unselectedToggleIsColored: true,
    fabRadius: 20.0,
    chipRadius: 20.0,
    cardRadius: 12.0,
    popupMenuOpacity: 0.90,
    popupMenuRadius: 8.0,
    dialogRadius: 20.0,
    timePickerDialogRadius: 20.0,
    bottomNavigationBarOpacity: 0.85,
    bottomNavigationBarElevation: 6.0,
    navigationBarOpacity: 0.85,
    navigationRailOpacity: 0.85,
    navigationRailElevation: 6.0,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  fontFamily: GoogleFonts.questrial().fontFamily,
);
