include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - prefer_single_quotes
    - avoid_print
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - require_trailing_commas
