include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports: true
    - prefer_single_quotes: true
    - avoid_print: true
    - always_put_control_body_on_new_line: true
    - require_trailing_commas: true
    - slash_for_doc_comments: true
