name: trdl_tool
description: TRDLtool

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flex_color_scheme: ^4.0.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter_spinkit: ^5.1.0
  firebase_analytics: ^8.3.2
  logger: ^1.1.0
  url_launcher: ^6.0.12
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/plotsklappsIconWhite400x400.png
  color_dark: "#000000"
  image_dark: assets/icons/plotsklappsIconBlack400x400.png
  android: true
  ios: true
  fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/welcome_screen/
    - assets/images/achtergrond_info/
    - assets/images/achtergrond_info/uitvoeren_plan/
    - assets/images/achtergrond_info/uitvoeren_plan/uitvoeren_plan_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/geplande_werkzaamheden/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/communicatie_middelen/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/communicatie_systeem/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/inzetten_railvoertuig/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/planopbouw_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/werkenmetplan_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/ari_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/vervoersregeling/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/elektrische_locs/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/diesel_locs/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/elektrische_treinen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/diesel_treinen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/rijtuigen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/onderhouds_machines/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/railweg_voertuigen/