name: trdl_tool
description: TRDLtool

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.9+29

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_riverpod: ^2.0.2
  flex_color_scheme: 6.0.1
  google_fonts: 3.0.1
  flutter_native_splash: ^2.2.11
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_core: 1.24.0
  flutter_spinkit: 5.1.0
  firebase_analytics: ^9.3.8
  firebase_app_check: ^0.0.9+1
  url_launcher: 6.1.6
  carousel_slider: 4.1.1
  url_launcher_web: 2.0.13

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/trdltool_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/trdltool_icon.png"

flutter_native_splash:
  color: "#EBF1EC"
  image: assets/icons/plotsklappsIconColorBorder.png
  color_dark: "#000000"
  image_dark: assets/icons/plotsklappsIconBlackWhite_512x512.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

    - assets/images/

    - assets/images/welcome_screen/

    - assets/images/achtergrond_info/

    - assets/images/achtergrond_info/uitvoeren_plan/
    - assets/images/achtergrond_info/uitvoeren_plan/uitvoeren_plan_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/geplande_werkzaamheden/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/communicatie_middelen/
    - assets/images/achtergrond_info/uitvoeren_plan/communicatie/communicatie_systeem/
    - assets/images/achtergrond_info/uitvoeren_plan/ncbg/
    - assets/images/achtergrond_info/uitvoeren_plan/dienstovergave/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/inzetten_icb/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/planopbouw_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/werkenmetplan_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/ari_basis/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/rijwegen_trots/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_rijwegen/rijwegen_bedienscherm/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/vervoersregeling/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/elektrische_locs/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/diesel_locs/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/elektrische_treinen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/diesel_treinen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/rijtuigen/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/onderhouds_machines/
    - assets/images/achtergrond_info/uitvoeren_plan/bijzonderheden_trein/basis_informatie/railweg_voertuigen/

    - assets/images/achtergrond_info/aanpassen_plan/
    - assets/images/achtergrond_info/aanpassen_plan/aanpassen_plan_basis/
    - assets/images/achtergrond_info/aanpassen_plan/orderacceptatie/
    - assets/images/achtergrond_info/aanpassen_plan/ongepland_werk/
    - assets/images/achtergrond_info/aanpassen_plan/incidenten/
    - assets/images/achtergrond_info/aanpassen_plan/vertragingen/

    - assets/images/achtergrond_info/incidenten/